<?php

$config = array(
    'market_cap' => array(
        $market_cap[] = ['value' =>'' ,'text' => 'Any'],
        $market_cap[] = ['value' =>'1_50000000' ,'text' => '1 million to 50 million'],
        $market_cap[] = ['value' =>'50000000_100000000' ,'text' => '50 million to 100 million'],
        $market_cap[] = ['value' =>'100000000_300000000' ,'text' => '100 million to 300 million'],
        $market_cap[] = ['value' =>'300000000_600000000' ,'text' => '300 million to 600 million'],
        $market_cap[] = ['value' =>'600000000_1000000000' ,'text' => '600 million to 1 billion'],
        $market_cap[] = ['value' =>'1000000000_5000000000' ,'text' => '1 billion to 5 billion'],
        $market_cap[] = ['value' =>'5000000000_' ,'text' => '5 billion or more'],
    ),

    'dividend_yield' => array(
        $dividend_yield[] = ['value' =>'' ,'text' => 'Any'],
        $dividend_yield[] = ['value' =>'0_10' ,'text' => '0 to 10'],
        $dividend_yield[] = ['value' =>'10_20' ,'text' => '10 to 20'],
        $dividend_yield[] = ['value' =>'20_30' ,'text' => '20 to 30'],
        $dividend_yield[] = ['value' =>'30_40' ,'text' => '30 to 40'],
        $dividend_yield[] = ['value' =>'40_50' ,'text' => '40 to 50'],
        $dividend_yield[] = ['value' =>'50_60' ,'text' => '50 to 60'],
        $dividend_yield[] = ['value' =>'60_70' ,'text' => '60 to 70'],
        $dividend_yield[] = ['value' =>'70_80' ,'text' => '70 to 80'],
        $dividend_yield[] = ['value' =>'80_90' ,'text' => '80 to 90'],
        $dividend_yield[] = ['value' =>'90_' ,'text' => '90 or more'],
    ),

    'current_volume' => array(
        $current_volume[] = ['value' =>'' ,'text' => 'Any'],
        $current_volume[] = ['value' =>'_50000' ,'text' => 'Under 50K'],
        $current_volume[] = ['value' =>'_100000' ,'text' => 'Under 100K'],
        $current_volume[] = ['value' =>'_500000' ,'text' => 'Under 500K'],
        $current_volume[] = ['value' =>'_750000' ,'text' => 'Under 750K'],
        $current_volume[] = ['value' =>'_1000000' ,'text' => 'Under 1M'],
        $current_volume[] = ['value' =>'0_' ,'text' => 'Over 0'],
        $current_volume[] = ['value' =>'50000_' ,'text' => 'Over 50K'],
        $current_volume[] = ['value' =>'100000_' ,'text' => 'Over 100K'],
        $current_volume[] = ['value' =>'200000_' ,'text' => 'Over 200K'],
        $current_volume[] = ['value' =>'300000_' ,'text' => 'Over 300K'],
        $current_volume[] = ['value' =>'400000_' ,'text' => 'Over 400K'],
        $current_volume[] = ['value' =>'500000_' ,'text' => 'Over 500K'],
        $current_volume[] = ['value' =>'750000_' ,'text' => 'Over 750K'],
        $current_volume[] = ['value' =>'1000000_' ,'text' => 'Over 1M'],
        $current_volume[] = ['value' =>'2000000_' ,'text' => 'Over 2M'],
        $current_volume[] = ['value' =>'5000000_' ,'text' => 'Over 5M'],
        $current_volume[] = ['value' =>'10000000_' ,'text' => 'Over 10M'],
    ),

    'price' => array(
        $price[] = ['value' =>'' ,'text' => 'Any'],
        $price[] = ['value' =>'_1' ,'text' => 'Under $1'],
        $price[] = ['value' =>'_2' ,'text' => 'Under $2'],
        $price[] = ['value' =>'_3' ,'text' => 'Under $3'],
        $price[] = ['value' =>'_4' ,'text' => 'Under $4'],
        $price[] = ['value' =>'_5' ,'text' => 'Under $5'],
        $price[] = ['value' =>'_7' ,'text' => 'Under $7'],
        $price[] = ['value' =>'_10' ,'text' => 'Under $10'],
        $price[] = ['value' =>'_15' ,'text' => 'Under $15'],
        $price[] = ['value' =>'_20' ,'text' => 'Under $20'],
        $price[] = ['value' =>'_30' ,'text' => 'Under $30'],
        $price[] = ['value' =>'_40' ,'text' => 'Under $40'],
        $price[] = ['value' =>'_50' ,'text' => 'Under $50'],
        $price[] = ['value' =>'1_' ,'text' => 'Over $1'],
        $price[] = ['value' =>'2_' ,'text' => 'Over $2'],
        $price[] = ['value' =>'3_' ,'text' => 'Over $3'],
        $price[] = ['value' =>'4_' ,'text' => 'Over $4'],
        $price[] = ['value' =>'5_' ,'text' => 'Over $5'],
        $price[] = ['value' =>'7_' ,'text' => 'Over $7'],
        $price[] = ['value' =>'10_' ,'text' => 'Over $10'],
        $price[] = ['value' =>'15_' ,'text' => 'Over $15'],
        $price[] = ['value' =>'20_' ,'text' => 'Over $20'],
        $price[] = ['value' =>'30_' ,'text' => 'Over $30'],
        $price[] = ['value' =>'40_' ,'text' => 'Over $40'],
        $price[] = ['value' =>'50_' ,'text' => 'Over $50'],
        $price[] = ['value' =>'60_' ,'text' => 'Over $60'],
        $price[] = ['value' =>'70_' ,'text' => 'Over $70'],
        $price[] = ['value' =>'80_' ,'text' => 'Over $80'],
        $price[] = ['value' =>'90_' ,'text' => 'Over $90'],
        $price[] = ['value' =>'100_' ,'text' => 'Over $100'],
        $price[] = ['value' =>'1_5' ,'text' => '$1 to $5'],
        $price[] = ['value' =>'1_10' ,'text' => '$1 to $10'],
        $price[] = ['value' =>'1_20' ,'text' => '$1 to $20'],
        $price[] = ['value' =>'5_10' ,'text' => '$5 to $10'],
        $price[] = ['value' =>'5_20' ,'text' => '$5 to $20'],
        $price[] = ['value' =>'5_50' ,'text' => '$5 to $50'],
        $price[] = ['value' =>'10_20' ,'text' => '$10 to $20'],
        $price[] = ['value' =>'10_50' ,'text' => '$10 to $50'],
        $price[] = ['value' =>'20_50' ,'text' => '$20 to $50'],
        $price[] = ['value' =>'50_100' ,'text' => '$50 to $100'],
    ),
    'ipo_date' => array(
        $ipo_date[] = ['value' =>'' ,'text' => 'Any'],
        $ipo_date[] = ['value' =>'1' ,'text' => 'Today'],
        $ipo_date[] = ['value' =>'2' ,'text' => 'Yesterday'],
        $ipo_date[] = ['value' =>'3' ,'text' => 'In the last week'],
        $ipo_date[] = ['value' =>'4' ,'text' => 'In the last month'],
        $ipo_date[] = ['value' =>'5' ,'text' => 'In the last quarter'],
        $ipo_date[] = ['value' =>'6' ,'text' => 'In the last year'],
        $ipo_date[] = ['value' =>'7' ,'text' => 'More than a year ago'],
        $ipo_date[] = ['value' =>'8' ,'text' => 'More than 5 years ago'],
        $ipo_date[] = ['value' =>'9' ,'text' => 'More than 10 years ago'],
        $ipo_date[] = ['value' =>'10' ,'text' => 'More than 15 years ago'],
        $ipo_date[] = ['value' =>'11' ,'text' => 'More than 20 years ago'],
        $ipo_date[] = ['value' =>'12' ,'text' => 'More than 25 years ago'],
    ),
    'change' => array(
        $change[] = ['value' =>'' ,'text' => 'Any'],
        $change[] = ['value' =>'1_' ,'text' => 'Up 1%'],
        $change[] = ['value' =>'2_' ,'text' => 'Up 2%'],
        $change[] = ['value' =>'3_' ,'text' => 'Up 3%'],
        $change[] = ['value' =>'4_' ,'text' => 'Up 4%'],
        $change[] = ['value' =>'5_' ,'text' => 'Up 5%'],
        $change[] = ['value' =>'6_' ,'text' => 'Up 6%'],
        $change[] = ['value' =>'7_' ,'text' => 'Up 7%'],
        $change[] = ['value' =>'8_' ,'text' => 'Up 8%'],
        $change[] = ['value' =>'9_' ,'text' => 'Up 9%'],
        $change[] = ['value' =>'10_' ,'text' => 'Up 10%'],
        $change[] = ['value' =>'15_' ,'text' => 'Up 15%'],
        $change[] = ['value' =>'20_' ,'text' => 'Up 20%'],
        $change[] = ['value' =>'_1' ,'text' => 'Down 1%'],
        $change[] = ['value' =>'_2' ,'text' => 'Down 2%'],
        $change[] = ['value' =>'_3' ,'text' => 'Down 3%'],
        $change[] = ['value' =>'_4' ,'text' => 'Down 4%'],
        $change[] = ['value' =>'_5' ,'text' => 'Down 5%'],
        $change[] = ['value' =>'_6' ,'text' => 'Down 6%'],
        $change[] = ['value' =>'_7' ,'text' => 'Down 7%'],
        $change[] = ['value' =>'_8' ,'text' => 'Down 8%'],
        $change[] = ['value' =>'_9' ,'text' => 'Down 9%'],
        $change[] = ['value' =>'_10' ,'text' => 'Down 10%'],
        $change[] = ['value' =>'_15' ,'text' => 'Down 15%'],
        $change[] = ['value' =>'_20' ,'text' => 'Down 20%'],
    ),

    '52_week_high' => array(
        $week_high[] = ['value' =>'' ,'text' => 'Any'],
        $week_high[] = ['value' =>'0_1' ,'text' => '0 to 1'],
        $week_high[] = ['value' =>'1_2' ,'text' => '1 to 2'],
        $week_high[] = ['value' =>'2_3' ,'text' => '2 to 3'],
        $week_high[] = ['value' =>'3_4' ,'text' => '3 to 4'],
        $week_high[] = ['value' =>'4_5' ,'text' => '4 to 5'],
        $week_high[] = ['value' =>'5_6' ,'text' => '5 to 6'],
        $week_high[] = ['value' =>'6_7' ,'text' => '6 to 7'],
        $week_high[] = ['value' =>'7_8' ,'text' => '7 to 8'],
        $week_high[] = ['value' =>'8_9' ,'text' => '8 to 9'],
        $week_high[] = ['value' =>'9_' ,'text' => '9 or more'],
    ),

);